// <auto-generated />
using System;
using BiodivApi.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BiodivApi.Migrations
{
    [DbContext(typeof(BiodivDbContext))]
    partial class BiodivDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BiodivApi.Entities.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("EncodedKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Permission")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("BiodivApi.Entities.LocalDistribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SpecieId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpecieId");

                    b.ToTable("LocalDistributions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "wwroot/LocalDistribution/1.png",
                            Place = "Bénin",
                            SpecieId = 1
                        });
                });

            modelBuilder.Entity("BiodivApi.Entities.LocalName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SpecieId")
                        .HasColumnType("integer");

                    b.Property<string>("Spelling")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("SpecieId");

                    b.ToTable("LocalNames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Language = "Fon",
                            SpecieId = 1,
                            Spelling = "Agbogbeton"
                        });
                });

            modelBuilder.Entity("BiodivApi.Entities.Specie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TaxonomicGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Threats")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Animal de couleur rougeâtre a noir en passant par le brun, il pèse pour un adulte de 265 a 320 kg pour le buffle de foret et de 500 a 700 kg pour le buffle de savane. Il est grégaire et peut former des groupes de plusieurs centaines de têtes. Il consomme plutôt des herbes et aime les endroits pas trop éloignés des points d’eau.",
                            EnglishName = "Buffalo",
                            Habitat = "Forets et savanes",
                            Name = "Buffle",
                            ScientificName = "Syncerus caffer",
                            Status = 5,
                            TaxonomicGroup = "Bovin; sous-famille des Bubalina",
                            Threats = "son habitat est de plus en plus dégradé, occupe par les champs et les habitations humaines. Par ailleurs, la viande étant très appréciée, l’espèce est menacée par le braconnage."
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            EnglishName = "Lion",
                            Habitat = "Forêts et savanes",
                            Name = "Lion",
                            ScientificName = "Panthera Leo",
                            Status = 4,
                            TaxonomicGroup = "Ordre des carnivores, famille des félidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            EnglishName = "Leopard",
                            Habitat = "Forêts et savanes",
                            Name = "Léopard",
                            ScientificName = "Panthera pardus",
                            Status = 4,
                            TaxonomicGroup = "Ordre des carnivores, famille des félidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            EnglishName = "Cheetah",
                            Habitat = "Savanes et déserts",
                            Name = "Guépard",
                            ScientificName = "Acinonyx jubatus",
                            Status = 4,
                            TaxonomicGroup = "Ordre des carnivores, famille des félidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            EnglishName = "Serval",
                            Habitat = "Savanes humides",
                            Name = "Serval",
                            ScientificName = "Leptailurus serval",
                            Status = 6,
                            TaxonomicGroup = "Ordre des carnivores, famille des félidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            EnglishName = "Caracal",
                            Habitat = "Savanes humides",
                            Name = "Caracal",
                            ScientificName = "Caracal caracal",
                            Status = 6,
                            TaxonomicGroup = "Ordre des carnivores, famille des félidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            EnglishName = "Hyena",
                            Habitat = "Savanes",
                            Name = "Hyène",
                            ScientificName = "Crocuta crocuta",
                            Status = 6,
                            TaxonomicGroup = "Ordre des carnivores, famille des hyenidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            EnglishName = "Striped jackal",
                            Habitat = "Savanes",
                            Name = "Chacal à flancs rayés",
                            ScientificName = "Canis adustus",
                            Status = 6,
                            TaxonomicGroup = "Ordre des carnivores, famille des canidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            EnglishName = "Golden jackal",
                            Habitat = "Savanes",
                            Name = "Chacal doré",
                            ScientificName = "Canis aureus",
                            Status = 6,
                            TaxonomicGroup = "Ordre des carnivores, famille des canidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            EnglishName = "Wild dog",
                            Habitat = "Savanes et steppes",
                            Name = "Lycaon",
                            ScientificName = "Lycaon pictus",
                            Status = 3,
                            TaxonomicGroup = "Ordre des carnivores, famille des canidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 11,
                            Description = "",
                            EnglishName = "Ichemon mongoose",
                            Habitat = "Savanes et steppes",
                            Name = "Mangouste icheumon",
                            ScientificName = "Herpestes ichneumon",
                            Status = 3,
                            TaxonomicGroup = "Ordre des carnivores, famille des herpestidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 12,
                            Description = "",
                            EnglishName = "White tailed mongoose",
                            Habitat = "Savanes et steppes",
                            Name = "Mangouste à queue blanche",
                            ScientificName = "Ichneumia albicauda",
                            Status = 3,
                            TaxonomicGroup = "Ordre des carnivores, famille des herpestidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 13,
                            Description = "",
                            EnglishName = "Marsh mongoose",
                            Habitat = "Savanes et steppes",
                            Name = "Mangouste des marais",
                            ScientificName = "Atilax paludinosus",
                            Status = 3,
                            TaxonomicGroup = "Ordre des carnivores, famille des herpestidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 14,
                            Description = "",
                            EnglishName = "Red mongoose",
                            Habitat = "Savanes et steppes",
                            Name = "Mangouste rouge",
                            ScientificName = "Herpestes sanguineus ",
                            Status = 3,
                            TaxonomicGroup = "Ordre des carnivores, famille des herpestidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 15,
                            Description = "",
                            EnglishName = "Civet",
                            Habitat = "Savanes et steppes",
                            Name = "Civette",
                            ScientificName = "Civettictis civetta",
                            Status = 3,
                            TaxonomicGroup = "Ordre des carnivores, famille des viverridés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 16,
                            Description = "",
                            EnglishName = "Nandinie",
                            Habitat = "Savanes et steppes",
                            Name = "Nandinie",
                            ScientificName = "Nandinia binotata",
                            Status = 3,
                            TaxonomicGroup = "Ordre des carnivores, famille des viverridés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 17,
                            Description = "",
                            EnglishName = "Genet",
                            Habitat = "Savanes et steppes",
                            Name = "Genette commune",
                            ScientificName = "Genetta genetta",
                            Status = 3,
                            TaxonomicGroup = "Ordre des carnivores, famille des viverridés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 18,
                            Description = "",
                            EnglishName = "Zorilla",
                            Habitat = "Savanes et steppes",
                            Name = "Zorille commun",
                            ScientificName = "Ictonyx striatus",
                            Status = 3,
                            TaxonomicGroup = "Ordre des carnivores, famille des mustélidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 19,
                            Description = "",
                            EnglishName = "Spotted otter",
                            Habitat = "Savanes et steppes",
                            Name = "Loutre à cou tacheté",
                            ScientificName = "Lutra maculicolis",
                            Status = 3,
                            TaxonomicGroup = "Ordre des carnivores, famille des mustélidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 20,
                            Description = "",
                            EnglishName = "White-cheeked otter",
                            Habitat = "Savanes et steppes",
                            Name = "Loutre à joues blanches",
                            ScientificName = "Aonyx capensis",
                            Status = 3,
                            TaxonomicGroup = "Ordre des carnivores, famille des mustélidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 21,
                            Description = "",
                            EnglishName = "Ratel",
                            Habitat = "Savanes et steppes",
                            Name = "Ratel",
                            ScientificName = "Mellivora capensis",
                            Status = 3,
                            TaxonomicGroup = "Ordre des carnivores, famille des mustélidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 22,
                            Description = "",
                            EnglishName = "Girafe",
                            Habitat = "Savanes et steppes",
                            Name = "Girafe",
                            ScientificName = "Giraffa camelopardalis",
                            Status = 3,
                            TaxonomicGroup = "Ordre des artiodactyles, famille des giraffidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 23,
                            Description = "",
                            EnglishName = "Céphalophe noir",
                            Habitat = "Savanes et steppes",
                            Name = "Black duiker",
                            ScientificName = "Cephalophus niger",
                            Status = 6,
                            TaxonomicGroup = "Ordre des artiodactyles, famille des bovidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 24,
                            Description = "",
                            EnglishName = "harnessed guib",
                            Habitat = "Savanes et steppes",
                            Name = "Guib harnaché",
                            ScientificName = "Tragelaphus scriptus",
                            Status = 6,
                            TaxonomicGroup = "Ordre des artiodactyles, famille des bovidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 25,
                            Description = "",
                            EnglishName = "Sitatunga",
                            Habitat = "Savanes et steppes",
                            Name = "Sitatunga",
                            ScientificName = "Tragelaphus spekei",
                            Status = 6,
                            TaxonomicGroup = "Ordre des artiodactyles, famille des bovidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 26,
                            Description = "",
                            EnglishName = "Grimm's duiker",
                            Habitat = "Savanes et steppes",
                            Name = "Céphalophe de grimm",
                            ScientificName = "Sylvicapra grimmia",
                            Status = 6,
                            TaxonomicGroup = "Ordre des artiodactyles, famille des bovidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 27,
                            Description = "",
                            EnglishName = "Red sided duiker",
                            Habitat = "Savanes et steppes",
                            Name = "Céphalophe à flancs roux",
                            ScientificName = "Cephalophus rufilatus",
                            Status = 6,
                            TaxonomicGroup = "Ordre des artiodactyles, famille des bovidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 28,
                            Description = "",
                            EnglishName = "Maxwell's duiker",
                            Habitat = "Forêt humide",
                            Name = "Céphalophe de Maxwell",
                            ScientificName = "Philantomba maxwelli",
                            Status = 6,
                            TaxonomicGroup = "Ordre des artiodactyles, famille des bovidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 29,
                            Description = "",
                            EnglishName = "Red-fronted gazelle",
                            Habitat = "Forêt humide",
                            Name = "Gazelle à front roux",
                            ScientificName = "Eudorcas rufifrons",
                            Status = 4,
                            TaxonomicGroup = "Ordre des artiodactyles, famille des bovidés",
                            Threats = ""
                        },
                        new
                        {
                            Id = 30,
                            Description = "",
                            EnglishName = "Ourébi",
                            Habitat = "Brousse, savane arborée, non loin de l'eau. Il peut vivre en plaine comme en montagne, jusqu'à 3 000 mètres d'altitude.",
                            Name = "Ourébi",
                            ScientificName = "Ourebia ourebi",
                            Status = 6,
                            TaxonomicGroup = "Ordre des artiodactyles, famille des bovidés",
                            Threats = ""
                        });
                });

            modelBuilder.Entity("BiodivApi.Entities.SpeciePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("SpecieId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpecieId");

                    b.ToTable("SpeciePhotos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Photo = "wwwroot/SpeciePhoto/1.png",
                            SpecieId = 1
                        });
                });

            modelBuilder.Entity("BiodivApi.Entities.LocalDistribution", b =>
                {
                    b.HasOne("BiodivApi.Entities.Specie", null)
                        .WithMany("LocalDistributions")
                        .HasForeignKey("SpecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiodivApi.Entities.LocalName", b =>
                {
                    b.HasOne("BiodivApi.Entities.Specie", null)
                        .WithMany("LocalNames")
                        .HasForeignKey("SpecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiodivApi.Entities.SpeciePhoto", b =>
                {
                    b.HasOne("BiodivApi.Entities.Specie", null)
                        .WithMany("SpeciePhotos")
                        .HasForeignKey("SpecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiodivApi.Entities.Specie", b =>
                {
                    b.Navigation("LocalDistributions");

                    b.Navigation("LocalNames");

                    b.Navigation("SpeciePhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
